### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by punyakrit** [punyakrit/social-share#1]
Redesign the readme file

**Comment by Heena31** [comment]
Kindly assign this issue to me as a GSSOC contribuor

**Comment by Heena31** [comment]
Readme file is updated Kindly look once.

**Comment by punyakrit** [comment]
Technology stack is not required and add step sto set up the project locally

**Comment by Heena31** [comment]
It is done, Kindly Check So that we can move forward

**Comment by punyakrit** [comment]
@Heena31 create a pr

**Comment by punyakrit** [comment]
Issue Solved
