### ISSUE TITLE
[Feat]: Explore Page

### ISSUE THREAD

**Issue by Prithwi32** [punyakrit/social-share#105]
### What would you like to share?

No contents in 'Explore' section
![image](https://github.com/punyakrit/social-share/assets/115262737/be0f9027-e3be-4b1c-a0c3-2ff28c23de98)

### Additional information

Could u suggest me what contents shall I add in explore section? like cards or some what components would u prefer?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
@punyakrit could you assign me this issue under gssoc'24

**Comment by punyakrit** [comment]
This section is not required
