### ISSUE TITLE
[Other] :  Adding the Home button 

### ISSUE THREAD

**Issue by namandude** [punyakrit/social-share#106]
### What would you like to share?

Hey while surfing the site i face the issue if i goes on to about or explore pages the is not button for returning to home page back , i would like to  add that int the site so that user dont need to find how to go back it should be clear to click on home and go back.

### Additional information

![Screenshot 2024-06-09 112156](https://github.com/punyakrit/social-share/assets/118013565/f690e76f-43c5-4942-b627-46400279af4c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punyakrit** [comment]
just click on app name to go to home screen
