### ISSUE TITLE
[Other] : Add new pages gallery

### ISSUE THREAD

**Issue by namandude** [punyakrit/social-share#108]
### What would you like to share?

I would like to add new page displaying the popular people who used our website to create there personal pages , in this component there will be swiper framer motion functionality will be there which displays our popular user , so that new customer trust us .

### Additional information

![Screenshot 2024-06-09 112715](https://github.com/punyakrit/social-share/assets/118013565/2a16aa1f-a43f-47a9-89f6-8207d7638fd9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punyakrit** [comment]
not required at the moment
