### ISSUE TITLE
[Other]: Creating a custom 404 not found page for your website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [punyakrit/social-share#110]
### What would you like to share?

![image](https://github.com/punyakrit/social-share/assets/125277258/7b8cb5af-61d6-49a1-8b6f-5ef0abf551e2)
it doesn't looks good

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punyakrit** [comment]
There is an error component already use it

**Comment by RamakrushnaBiswal** [comment]
its good solved
