### ISSUE TITLE
Addition of Error 404 page.

### ISSUE THREAD

**Issue by taneeshaa15** [punyakrit/social-share#116]
### What would you like to share?

I will add error 404 webpage.

### Additional information

This will redirect the user to home page after a timespan if the user mistyped the url or came across any removed page.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by taneeshaa15** [comment]
@punyakrit Please assign me this issue under gssoc'24 level 2.

**Comment by punyakrit** [comment]
same issue has already been assigned #110

**Comment by taneeshaa15** [comment]
I will enhance that issue by giving interactive UI and redirection element.

**Comment by punyakrit** [comment]
its element is already there
<img width="1164" alt="Screenshot 2024-06-10 at 10 11 47 PM" src="https://github.com/punyakrit/social-share/assets/67222925/d973a461-ffe1-47db-8f0e-7e70a536f6c9">
