### ISSUE TITLE
Enhance the website Background

### ISSUE THREAD

**Issue by naisargi17** [punyakrit/social-share#117]
### What would you like to share?

https://ui.aceternity.com/components/hero-highlight
this background will look better with your website.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punyakrit** [comment]
can use for home page

**Comment by naisargi17** [comment]
Thank you punyakrit .

**Comment by punyakrit** [comment]
just keep the footer as it is and place the bg on hero section

**Comment by naisargi17** [comment]
> just keep the footer as it is and place the bg on hero section

This looks better i think

https://github.com/punyakrit/social-share/assets/111778403/698b80e9-d6d7-4848-b341-d193bc70a6ed

**Comment by punyakrit** [comment]
Yeah looks fine
