### ISSUE TITLE
[Bug]: Hamburger icon should replace with close icon if dialog open up after click on hamburger

### ISSUE THREAD

**Issue by kapilG0** [punyakrit/social-share#120]
### What happened?

![image](https://github.com/punyakrit/social-share/assets/59639410/aabdb1ec-99d9-4a3c-8727-e3a27042e25b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @punyakrit please assign this issue to me under gssoc 24

**Comment by kapilG0** [comment]
i think this issue is resolved by someone else previously hamburger was showing now not showing even in mobile 
![image](https://github.com/punyakrit/social-share/assets/59639410/9e6149e0-125b-4521-bfe9-6fbafe9297df)
please close thanks

**Comment by punyakrit** [comment]
<img width="574" alt="Screenshot 2024-06-18 at 4 36 33 PM" src="https://github.com/punyakrit/social-share/assets/67222925/7cae59bb-3e2d-4572-b818-68706c85fb8c">
it is there your repo might not be updated

**Comment by kapilG0** [comment]
> <img alt="Screenshot 2024-06-18 at 4 36 33 PM" width="574" src="https://private-user-images.githubusercontent.com/67222925/340651162-7cae59bb-3e2d-4572-b818-68706c85fb8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTQyOTQsIm5iZiI6MTcxODcxMzk5NCwicGF0aCI6Ii82NzIyMjkyNS8zNDA2NTExNjItN2NhZTU5YmItM2UyZC00NTcyLWI4MTgtNjg3MDZjODVmYjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDEyMzMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMDgxZTkyYzg4NjgxNWQ0OGVhYjg2OTI4YmFjMzM1MmQ4NTMyNGEyZDU4MGQzYjZmNjdiY2M5Nzg2NzI0MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xn36FGHdYx4b5rQFLE17c6BWIW2Bev9pyqw8t3QY8KI"> it is there your repo might not be updated

Ok let me check please opened this issue sorry I closed it

**Comment by kapilG0** [comment]
Hello @punyakrit i raised pr #144  please check thanks
