### ISSUE TITLE
Add Icons to Navbar 

### ISSUE THREAD

**Issue by sailaja-adapa** [punyakrit/social-share#142]
### What would you like to share?

Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add Icons to Navbar so that it will increase website Attractiveness 

Can you please assign me this issue under gssoc'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sailaja-adapa** [comment]
@punyakrit can you assign me this issue under GSSOC'24

**Comment by punyakrit** [comment]
this is not required
