### ISSUE TITLE
[Other] International country code for phone number

### ISSUE THREAD

**Issue by AkhilaSunesh** [punyakrit/social-share#155]
### What would you like to share?

Location: Contact section
![image](https://github.com/punyakrit/social-share/assets/140897461/da410d23-66cd-4179-a3e1-7dfac96884ad)
![image](https://github.com/punyakrit/social-share/assets/140897461/b6cc7aeb-2188-4294-8505-dcfdfb5ef776)
Introduce dropdowns for city, Country and phone code.
Kindly assign this issue to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punyakrit** [comment]
the whole page will get redesign cant have this for now
