### ISSUE TITLE
Feature ✨: Add scroll to top button

### ISSUE THREAD

**Issue by TheNikhilRaj** [punyakrit/social-share#157]
### What would you like to share?

Hey @punyakrit  ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no scroll to top button present on the website, which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

Screenshot(Mandatory):
![339382743-2a95bcea-4b73-4a77-961d-faac30bbcea7](https://github.com/punyakrit/social-share/assets/129590267/0e11b5f1-97f6-47eb-8334-ece4a8c26706)
@punyakrit  ,Could you please assign me this issue under gssoc'24 ?

Are you contributing under any open-source program ?
GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punyakrit** [comment]
none of the page are lengthy for now so don't require it
