### ISSUE TITLE
Add "Company" Links to "Footer"

### ISSUE THREAD

**Issue by MastanSayyad** [punyakrit/social-share#159]
### What would you like to share?

@punyakrit 

The footer section of the website lacks essential navigation links under the "Company" section. It would be beneficial to add a list of links to improve user navigation and provide easy access to key pages.

Under the **"Company"** section in the footer, include the following links:

- Home
- About
- Contact
- Contributor

![image](https://github.com/punyakrit/social-share/assets/101971980/75547dd6-fa97-44d0-88d1-1ee2969e2685)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punyakrit** [comment]
not required
