### ISSUE TITLE
[Feat]: Implement Workflow for closing Old PRs

### ISSUE THREAD

**Issue by Asymtode712** [punyakrit/social-share#16]
This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

![Close Old PRs](https://github.com/punyakrit/social-share/assets/115717746/1d6acf71-f868-4cc6-ae5f-2a936e5e9734)

**Comment by Asymtode712** [comment]
@punyakrit please assign me this issue

**Comment by punyakrit** [comment]
@Asymtode712  can you create a single issue stating #11  #12  #13  #14  #15  #16
