### ISSUE TITLE
Add "Scroll Down Progress Bar" for Enhanced Navigation

### ISSUE THREAD

**Issue by MastanSayyad** [punyakrit/social-share#160]
### What would you like to share?

Hey @punyakrit 

- The website would benefit from the addition of a **scroll-down progress bar** that appears on all pages, particularly useful for longer pages such as **"Contributors".** 
- This feature will enhance user navigation by providing a visual indicator of their progress through the content.

**Like This:**

![image](https://github.com/punyakrit/social-share/assets/101971980/9eb0abc8-9492-404a-8000-02aa60bfe1e2)

Could you please assign this issue to me under GSSOC 24?

### Additional information

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punyakrit** [comment]
dont require for now as ui is pretty simple
