### ISSUE TITLE
Add Fevicon tp The website

### ISSUE THREAD

**Issue by MastanSayyad** [punyakrit/social-share#161]
### What would you like to share?

@punyakrit I would like to add a fevicon to the website

![image](https://github.com/punyakrit/social-share/assets/101971980/7f5c53a4-d09b-45a2-9d92-63ed5f0f4e5d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punyakrit** [comment]
<img width="1135" alt="Screenshot 2024-06-28 at 4 04 23 AM" src="https://github.com/punyakrit/social-share/assets/67222925/7cb4d829-1618-4e3d-8267-94399a76f6d3">
Your previous commit broke dashboard ui can you fix it in different issue

**Comment by MastanSayyad** [comment]
@punyakrit Yes i can see the back to home button at the left corner, I'll remove it and fix it, Thanks for letting me know!
