### ISSUE TITLE
Home Page User Name text field has awkward outline 

### ISSUE THREAD

**Issue by Abdev1205** [punyakrit/social-share#17]
Home Page User Name text field has awkward outline 
![image](https://github.com/punyakrit/social-share/assets/100786143/2118cbcd-3b47-4324-ba14-bd8dfe14e796)

Please assign me this task as per GSSOC 24 rules and regulations

I want to make it more beautiful and with better user experience

**Comment by punyakrit** [comment]
@Abdev1205 you can work on this issue
