### ISSUE TITLE
[Feature Request]: Dockerize the app

### ISSUE THREAD

**Issue by Dhruv-Pattel** [punyakrit/social-share#174]
### What would you like to share?

- Dockerfile setup
- compose.yaml file for live changes
- documentation for running containers

dockerizing the application is needed for deployment. I can add all these features.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punyakrit** [comment]
Currently website is hosted on vercel might not require to be dockerized yet
