### ISSUE TITLE
[Other] Design a testimonials page

### ISSUE THREAD

**Issue by komal-agarwal5** [punyakrit/social-share#178]
### What would you like to share?

I want to design testimonials using inifinite movinf carousel cards which can be added as a subsection in any page or even as an independent page

### Additional information

This will help to attract users to this website

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punyakrit** [comment]
dont require it for now
