### ISSUE TITLE
Add Icons to Navbar 

### ISSUE THREAD

**Issue by sailaja-adapa** [punyakrit/social-share#184]
### What would you like to share?

Hello Project Admin
I would like to add icons to Navbar to make website look attractive
Can you assign me this issue under GSSOC'24

![IMG_20240708_142116](https://github.com/punyakrit/social-share/assets/161804629/3a221bbb-98d6-4327-9949-f5898871b9a5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punyakrit** [comment]
Dont require this feature

**Comment by sailaja-adapa** [comment]
But I think it will be good if we add icons to Navbar it will make our website to look attractive @punyakrit

**Comment by punyakrit** [comment]
i need to redesign the landing page of the website so dont think it would be required for now

**Comment by sailaja-adapa** [comment]
Yeah okk @punyakrit 
Thank you ☺️
