### ISSUE TITLE
Adding hover effect on buttons like register and join for free.

### ISSUE THREAD

**Issue by pahuja-sahil** [punyakrit/social-share#20]
![image](https://github.com/punyakrit/social-share/assets/140882358/10e4a03a-e30b-40a4-b2f3-236d0bf25cd6)

we can add a nice hover effect on the two buttons and also on the things listed in the navbar like contack , explore for better look. It will look good and add a nice touch to the website.

@punyakrit I would rely like to work on this issue  under gssoc level1.
kindly assign this issue to me.

thank you.

**Comment by SaranshBangar** [comment]
@pahuja-sahil Are you working under this issue? Because I have resolved it and am ready to raise a PR
