### ISSUE TITLE
[feat] : Add Login Signup with email 

### ISSUE THREAD

**Issue by dhruv8433** [punyakrit/social-share#212]
### What would you like to share?

@punyakrit 

we can add login form somethign like this 
and store user info in localstorage or databasse 

![image](https://github.com/user-attachments/assets/65a109c4-0005-426f-9d1f-048e7c10374d)

![image](https://github.com/user-attachments/assets/c1e65bcc-758a-4520-a068-4acbaad358af)

### Additional information

it will help user to provider other login types

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punyakrit** [comment]
we are following google auth signup its better for now dont require custom signup option
