### ISSUE TITLE
[Bug]: we should try to truncate the username of contributor 

### ISSUE THREAD

**Issue by Varsani2520** [punyakrit/social-share#232]
### What happened?

in contributor card name is so long then not fit in the card so we can try to fit that we have option is truncate the name so it absolutely fit in the card .
![image](https://github.com/user-attachments/assets/57adaeab-13a4-4a3c-9e4d-59ede0e086ad)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@punyakrit ,assign me 
i do my best

**Comment by punyakrit** [comment]
after creating issue you can directly make pr it takes time to open and see all issue first then assign

**Comment by Varsani2520** [comment]
I understood your situation @punyakrit

**Comment by Varsani2520** [comment]
Thank you :)
