### ISSUE TITLE
contribute card is not proper content goes out of card

### ISSUE THREAD

**Issue by Utsavladia** [punyakrit/social-share#236]
### What happened?

![image](https://github.com/user-attachments/assets/77187222-3563-41fe-a4ba-40e14f6d3d91)

this should be fixed to have a proper professional look of the website

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punyakrit** [comment]
this issue has already been taken
