### ISSUE TITLE
Enhance Dashboard to Include User Settings and Sharing Options

### ISSUE THREAD

**Issue by kom-senapati** [punyakrit/social-share#30]
![image](https://github.com/punyakrit/social-share/assets/92045934/361fd207-c42f-4809-8c0f-ef8ab6a9df05)

- Expand the current dashboard to include settings for changing the username and full name.
- Add options to edit additional details, such as social links.
- Implement a 'Share Your URL' button to facilitate sharing with other users.

These enhancements will provide users with greater control over their profile and make it easier to share their information.

**Comment by punyakrit** [comment]
I am building that part

**Comment by kom-senapati** [comment]
> I am building that part

Then you can assign yourself this issue
