### ISSUE TITLE
[UI] : Change title name to "ShareHub"

### ISSUE THREAD

**Issue by SaranshBangar** [punyakrit/social-share#34]
Description -> The current web title is the default "Create Next App" instead of "ShareHub"

Image ->

![image](https://github.com/punyakrit/social-share/assets/114401238/032de893-62ea-4286-88dc-dec40dd723bc)

**Comment by punyakrit** [comment]
would you like to work on this issue

**Comment by SaranshBangar** [comment]
> would you like to work on this issue

Yes sir, I have already resolved it, will raise the PR within the next few minutes

**Comment by SaranshBangar** [comment]
Resolved in PR #35

**Comment by punyakrit** [comment]
Thanks for contributing
