### ISSUE TITLE
[UI] : Hover effects on navbar links

### ISSUE THREAD

**Issue by SaranshBangar** [punyakrit/social-share#36]
Description -> As of now the navbar are static text without any effects or links

Image ->

![image](https://github.com/punyakrit/social-share/assets/114401238/4cfaeb12-50fa-497a-970f-9c3e2049fd62)

Note -> I am a contributor under GSSoC, please do label this issue accordingly

**Comment by punyakrit** [comment]
issue has already been listed #20

**Comment by SaranshBangar** [comment]
> issue has already been listed #20

Can I close this issue and raise a PR under that one?

**Comment by punyakrit** [comment]
can ask the assigned person if they are working on that issue

**Comment by SaranshBangar** [comment]
Ok sir

**Comment by punyakrit** [comment]
fixed
