### ISSUE TITLE
Responsiveness of main page

### ISSUE THREAD

**Issue by kashnx** [punyakrit/social-share#39]
**Issue Description:**
The main page of the application is not fully responsive, leading to layout issues and poor user experience on various devices, especially on mobile and tablet screens. The page needs to be redesigned and optimized to ensure it adapts smoothly to different screen sizes.

**Request:**
Please assign this issue to me. I will work on making the main page fully responsive, ensuring it provides an optimal user experience across all devices.

Thank you!

**Comment by punyakrit** [comment]
@aakashsharma7  issue has already been assigned to @kashnx
