### ISSUE TITLE
Missing About Us Page, Contact us form and explore page

### ISSUE THREAD

**Issue by r7projects-shayan** [punyakrit/social-share#5]
## Issue Description 

Currently there is no about us page, contact us form and explore page for the website. The navbar buttons are non functional

## Solution

A proper, responsive and dedicated About Us Page, Contact Us form and explore page matching the websites purpose and theme color

Functional Navbar Links

## Status

Urgent

## Program 

Gssoc 24

**Comment by r7projects-shayan** [comment]
@punyakrit I will solve this major issue. Kindly assign this to me

**Comment by punyakrit** [comment]
@r7projects-shayan  you can start working on the issue

**Comment by r7projects-shayan** [comment]
@punyakrit Thanks

**Comment by punyakrit** [comment]
@r7projects-shayan  are you working on this issue?

**Comment by r7projects-shayan** [comment]
Yes I am @punyakrit

**Comment by punyakrit** [comment]
great @r7projects-shayan

**Comment by punyakrit** [comment]
@r7projects-shayan  status?

**Comment by r7projects-shayan** [comment]
@punyakrit I had some network issues, since the past two days. The pages are completely ready, just fixing the navbar, will submit within today itself
