### ISSUE TITLE
Adding dashboard buttons once the user has logged in and some more.

### ISSUE THREAD

**Issue by Stiffpixels** [punyakrit/social-share#57]
- There is no way to get to the dashboard for logged in users at this point.

![image](https://github.com/punyakrit/social-share/assets/32983571/c8774c16-df0c-4ffd-8b09-559978e8536b)

- The cursor is small in comparison to the text it should have the same height.

![image](https://github.com/punyakrit/social-share/assets/32983571/87b5316e-d57f-4312-a52a-700e9ffd42fb)

- The X logo looks like a cross.

![image](https://github.com/punyakrit/social-share/assets/32983571/66d50883-dc3a-4849-a160-db2fe5ce3e1c)

**Comment by punyakrit** [comment]
#27  issue has already need assigned you can work on rest of these issues

**Comment by Stiffpixels** [comment]
can you add the level label as well

**Comment by punyakrit** [comment]
Will add that depending on no of lines update
