### ISSUE TITLE
Navbar is not responsive

### ISSUE THREAD

**Issue by r7projects-shayan** [punyakrit/social-share#6]
## Issue Description

The Navbar lacks interactivity and is not responsive for smaller and medium sized devices

## Solutions

Responsive Navbar with proper hover effects and interactivity

## Screenshots to fix

![Screenshot 2024-05-27 163018](https://github.com/punyakrit/social-share/assets/167475552/9e58756d-c80a-4925-9e93-c2dcb3f00edd)

## Program

Gssoc 24

**Comment by r7projects-shayan** [comment]
@punyakrit Kindly assign this issue to me

**Comment by punyakrit** [comment]
@r7projects-shayan  can work on this issue

**Comment by r7projects-shayan** [comment]
@punyakrit alright

**Comment by lassmara** [comment]
Please assign me this issue.
