### ISSUE TITLE
[UI] : Addition of custom scroll bar

### ISSUE THREAD

**Issue by SaranshBangar** [punyakrit/social-share#72]
Description -> As of now the website uses the default scroll bar provided by the browser, we can change it and add a custom scroll bar to elevate UX and user retention time

Image ->

![image](https://github.com/punyakrit/social-share/assets/114401238/f9614bab-ac52-4b18-964c-abbb4b4797e4)

**Comment by SaranshBangar** [comment]
Resolved in PR #73

**Comment by punyakrit** [comment]
can try otherwise i thinking of making no scrollbar

**Comment by SaranshBangar** [comment]
I can do that too sir @punyakrit

**Comment by SaranshBangar** [comment]
Sir, since this issue is completed, should I open a new issue to remove the scrollbar? @punyakrit

**Comment by punyakrit** [comment]
leave that part @SaranshBangar  see if you can improve now the design of dashboard page

**Comment by SaranshBangar** [comment]
Ok sir

**Comment by punyakrit** [comment]
no @SaranshBangar  i already have added code of no scrollbar

**Comment by SaranshBangar** [comment]
Sir can I open a general issue by the title "Improving dashboard page" as there are multiple small changes that can be done in it
@punyakrit

**Comment by punyakrit** [comment]
yes you can work on design of dashboard i am also working now on profile view page

**Comment by punyakrit** [comment]
dont just change any functionality

**Comment by SaranshBangar** [comment]
Ok sir

**Comment by SaranshBangar** [comment]
Sir, I am a little busy today and tomorrow, is it fine if I raise a PR for this tomorrow EOD? @punyakrit
