### ISSUE TITLE
Designing Frontend of login/Signin page 

### ISSUE THREAD

**Issue by ManpreetSingh18** [punyakrit/social-share#75]
I can design Login/Signin page according to your website UI and theme . Below is the sample 
![Screenshot 2024-06-02 175340](https://github.com/punyakrit/social-share/assets/72294811/da9298d7-542e-44c6-945f-b1844d2d76b3)
Please assign this issue to me under GSSoc

**Comment by punyakrit** [comment]
not required at the moment
