### ISSUE TITLE
Designing Error 404 page 

### ISSUE THREAD

**Issue by ManpreetSingh18** [punyakrit/social-share#76]
When a user clicks on a page that is not defined an Error page should come to tell them and give option to redirect to the Home Page. I can make this page according to your website UI and theme .
Current scenario
![Screenshot 2024-06-02 175526](https://github.com/punyakrit/social-share/assets/72294811/f2ca6095-9067-4a21-ad60-154b2629d79c)
Expected results 
![Screenshot 2024-06-02 153718](https://github.com/punyakrit/social-share/assets/72294811/dd561a0a-2ed6-41a7-8f8b-c37e0ac779a2)
Please assign this issue to me under GSSoc

**Comment by punyakrit** [comment]
you can work on this issue

**Comment by ManpreetSingh18** [comment]
For the env variable are there any sample env values or do I need to use mine API by making an account as it is asking for credit card in google Cloud?

**Comment by punyakrit** [comment]
Google api doesn’t require credit cards can create your own for free
