### ISSUE TITLE
Update Dashboard

### ISSUE THREAD

**Issue by Heena31** [punyakrit/social-share#87]
### What happened?

![image](https://github.com/punyakrit/social-share/assets/79543358/76dedffd-fe5b-465b-9706-845a47a28599)
In the above image in the left side there is side bar which is not visible in the small screen.

In the mobile view also the navbar is not visible. 
![image](https://github.com/punyakrit/social-share/assets/79543358/ea749b14-81e5-468b-8351-b5c51c7e5492)

Kindly Assign issue to me. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punyakrit** [comment]
fixed
