### ISSUE TITLE
Add Footer in the landing page

### ISSUE THREAD

**Issue by Heena31** [punyakrit/social-share#9]
I would like to create footer for the landing page. As a Gssoc contributor, I would like you to assign this issue to me

**Comment by Amrapali06** [comment]
hey , would like to slove this issue

**Comment by Heena31** [comment]
@punyakrit Hey, Kindly share the information you want me to add in the footer

**Comment by punyakrit** [comment]
you can give a try and share design once of footer still not clear about the idea

**Comment by Heena31** [comment]
![image](https://github.com/punyakrit/social-share/assets/79543358/50ba75c2-d238-4c92-979e-0e57a7084f72)
Kindly check once and let me know if you want any change

**Comment by punyakrit** [comment]
Remove the resource section
If you have added legal , add - Privacy Policy & T&C  page for them also

**Comment by Heena31** [comment]
@punyakrit what should i am suppose to add into the privacy and tc kindly share the content for them.

**Comment by punyakrit** [comment]
Yeah looks fine

**Comment by Heena31** [comment]
@punyakrit may i do pr?
