### ISSUE TITLE
DOC: Adding workflows 

### ISSUE THREAD

**Issue by d1vyadharsh1n1** [punyakrit/social-share#90]
### What's wrong with the existing documentation

I would like to add greeting.yml file to the project. Kindly assign me this under gssoc.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by punyakrit** [comment]
can you explain the problem more

**Comment by d1vyadharsh1n1** [comment]
This will help generating automated welcoming messages for new contributors issues and prs.
